[package]
name = "mixedradix"
version = "1.0.0-pre+3"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/savmlang/mixedradix"
homepage = "https://github.com/savmlang/mixedradix?tab=readme-ov-file"
authors = ["Akshanabha Chakraborty <ahqsecret@gmail.com> (@ahqsoftwares)"]
description = "MixedRadix arithmatic made simpler"

[dependencies]
mixedradix_macros = { version = "=1.0.0-pre+3", path = "./macros" }
serde = { version = "^1", default-features = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
serde = ["dep:serde"]
